# Generated by Django 3.2.4 on 2021-08-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210820_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='https://lalit-crm-bucket.s3.us-west-2.amazonaws.com/images/profPic.png', null=True, upload_to=''),
        ),
    ]
